# Generated by Django 4.2.7 on 2024-10-31 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_nguoidung_lichsu_alter_trang_chap_lichsu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lichsu',
        ),
    ]
