# Generated by Django 4.2.7 on 2024-10-31 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_delete_lichsu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lichsu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idchap', models.IntegerField()),
                ('idtruyen', models.IntegerField()),
                ('stt', models.FloatField(default=0)),
                ('tentruyen', models.CharField(max_length=255)),
                ('anhbia', models.FileField(upload_to='anhbia/')),
                ('thoigiandoc', models.DateTimeField(auto_now_add=True)),
                ('nguoidoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lichsu', to='myapp.nguoidung')),
            ],
        ),
    ]
