# Generated by Django 4.2.7 on 2024-11-14 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_thongbao_chap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thongbao',
            name='chap',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chap', to='myapp.chap'),
        ),
    ]
