# Generated by Django 4.2.7 on 2024-11-14 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_thongbao_chap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thongbao',
            name='chap',
        ),
    ]
