# Generated by Django 4.2.7 on 2024-11-14 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_remove_thongbao_chap'),
    ]

    operations = [
        migrations.AddField(
            model_name='thongbao',
            name='chap',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='chap', to='myapp.chap'),
        ),
    ]
